spring:
  cloud:
    stream:
        bindings:
          input:
            consumer:
              autoCommitOnError: true
          custom_dlq:
            destination: custom_dlq
        kafka:
           binder:
             brokers: 192.168.99.100
             zkNodes: 192.168.99.100
